import React, { useEffect, useRef, useState } from "react";
import axios from "axios";

import {
    CalendarDays,
    Tag,
    Quote,
} from "lucide-react";

import {
    FaFacebookF,
    FaWhatsapp,
    FaLinkedinIn,
} from "react-icons/fa6";

import "./Blogdetail.css";

import q1 from "../../assets/Aboutimages/q1.png";
import a5 from "../../assets/Main/a5.png";

const API_URL = "http://localhost:5000/api";

// ======================================================
// DEFAULT DATA
// ======================================================

const defaultData = {
    hero: {
        title: "A Complete Guide to Solar Energy for Homeowners",
        backgroundImage: "",
        date: "February 27, 2026",
        category: "Residential Solar",
    },

    featureImage: "",

    intro: {
        paragraph1:
            "Switching to solar energy is one of the smartest decisions homeowners can make today. With rising electricity costs & growing environmental concerns, solar power offers a clean, reliable, and cost-effective solution. This guide will walk you through everything you need to know about solar energy from how it works to how you can benefit from it in your daily life.",

        paragraph2:
            "Solar energy is generated by capturing sunlight using solar panels and converting it into usable electricity. These panels produce direct current (DC) power, which is then converted into alternating current (AC) power by an inverter so it can be used in your home. Any excess energy can be sent back to the grid or stored in batteries for later use.",
    },

    quote:
        "Harnessing the power of the sun not only helps you save on electricity bills but also contributes to a cleaner environment, greater energy independence, and a more sustainable future for your home and family.",

    benefits:
        "Solar power helps reduce your monthly electricity bills, protects you from rising energy prices, & lowers your carbon footprint. It also increases your energy independence and can add long-term value to your property. With battery storage, you can even keep your home powered during outages.",

    installation: {
        heading: "Understanding installation and costs",

        description:
            "The installation process usually includes site inspection, system design, approvals, installation, and final testing. While the upfront cost may seem significant, solar systems typically pay for themselves over time through energy savings and incentives, making them a smart long term investment.",
    },

    installationSteps: [
        "While there is an upfront investment, long-term savings on electricity bills & possible incentives help recover costs over time.",

        "Professional technician install a system, connect all component & test performance to ensure everything work safely & efficiently.",

        "Necessary permits, grid approvals, and paperwork are handled to ensure a smooth and compliant installation process.",

        "Based on the assessment a customized system is designed & transparent cost estimate is provided with no hidden charges.",

        "A detailed inspection of your property & energy usage helps determine the right system size, layout & expected performance.",
    ],

    carbonFootprint:
        "One of the most effective ways to lower your carbon footprint is by reducing energy consumption. Simple steps like using energy-efficient appliances, switching to LED lighting, and turning off devices when not in use can significantly cut down on emissions. Choosing renewable energy sources, where available, further helps minimize dependence on fossil fuels and supports cleaner power generation.",

    tags: [
        "Green Energy",
        "Solar Energy",
        "Sustainable Energy",
    ],

    social: {
        facebook: "#",
        whatsapp: "#",
        linkedin: "#",
    },

    comments: {
        title: "Leave a Reply",

        description:
            "Your email address will not be published. Required fields are marked *",

        commentLabel: "Comment *",

        nameLabel: "Name *",

        emailLabel: "Email *",

        websiteLabel: "Website",

        saveDetailsText:
            "Save my name, email, and website in this browser for the next time I comment.",

        buttonText: "Post Comment",
    },
};

// ======================================================
// FIND LATEST BLOG DETAILS RECORD
// ======================================================

const getLatestBlogDetail = (pages) => {
    if (!Array.isArray(pages)) {
        return null;
    }

    const blogPages = pages.filter((page) => {
        const pageName = String(
            page.pageName || page.page_name || ""
        )
            .trim()
            .toLowerCase();

        const sectionName = String(
            page.sectionName || page.section_name || ""
        )
            .trim()
            .toLowerCase();

        const validPageName =
            pageName === "blog details" ||
            pageName === "blog detail" ||
            pageName === "blogdetail";

        const validSectionName =
            sectionName === "blog details" ||
            sectionName === "blog detail" ||
            sectionName === "blogdetail";

        return validPageName && validSectionName;
    });

    if (blogPages.length === 0) {
        return null;
    }

    // IMPORTANT:
    // If duplicate Blog Details records exist,
    // always use the latest/highest ID record.
    return blogPages.reduce((latest, current) => {
        return Number(current.id) > Number(latest.id)
            ? current
            : latest;
    });
};

// ======================================================
// SAFE MERGE CMS DATA
// ======================================================

const mergeBlogData = (content) => {
    const safeContent =
        content && typeof content === "object"
            ? content
            : {};

    return {
        ...defaultData,

        ...safeContent,

        hero: {
            ...defaultData.hero,
            ...(safeContent.hero || {}),
        },

        intro: {
            ...defaultData.intro,
            ...(safeContent.intro || {}),
        },

        installation: {
            ...defaultData.installation,
            ...(safeContent.installation || {}),
        },

        social: {
            ...defaultData.social,
            ...(safeContent.social || {}),
        },

        comments: {
            ...defaultData.comments,
            ...(safeContent.comments || {}),
        },

        installationSteps:
            Array.isArray(safeContent.installationSteps)
                ? safeContent.installationSteps
                : [...defaultData.installationSteps],

        tags:
            Array.isArray(safeContent.tags)
                ? safeContent.tags
                : [...defaultData.tags],
    };
};

// ======================================================
// BLOG DETAIL COMPONENT
// ======================================================

const BlogDetail = () => {
    const [data, setData] = useState(defaultData);

    const [visibleItems, setVisibleItems] = useState([]);

    const sectionRefs = useRef([]);

    // ==================================================
    // LOAD BLOG DETAILS FROM CMS
    // ==================================================

    useEffect(() => {
        const loadBlogDetails = async () => {
            try {
                const response = await axios.get(
                    `${API_URL}/pages`
                );

                const pages = Array.isArray(response.data)
                    ? response.data
                    : Array.isArray(response.data?.pages)
                        ? response.data.pages
                        : [];

                console.log(
                    "BLOG DETAILS - TOTAL CMS RECORDS:",
                    pages.length
                );

                // IMPORTANT:
                // Do NOT use .find() here.
                // .find() can return an older Blog Details record.
                const blogDetailPage =
                    getLatestBlogDetail(pages);

                if (!blogDetailPage) {
                    console.log(
                        "BLOG DETAILS CMS RECORD NOT FOUND - USING DEFAULT DATA"
                    );

                    return;
                }

                console.log(
                    "BLOG DETAILS - SELECTED RECORD:",
                    blogDetailPage
                );

                console.log(
                    "BLOG DETAILS - SELECTED ID:",
                    blogDetailPage.id
                );

                const content =
                    blogDetailPage.content &&
                        typeof blogDetailPage.content === "object"
                        ? blogDetailPage.content
                        : {};

                console.log(
                    "BLOG DETAILS - CMS CONTENT:",
                    content
                );

                const mergedData =
                    mergeBlogData(content);

                console.log(
                    "BLOG DETAILS - FINAL DATA:",
                    mergedData
                );

                setData(mergedData);
            } catch (error) {
                console.error(
                    "BLOG DETAILS LOAD ERROR:",
                    error
                );
            }
        };

        loadBlogDetails();
    }, []);

    // ==================================================
    // SCROLL REVEAL ANIMATION
    // ==================================================

    useEffect(() => {
        const observer = new IntersectionObserver(
            (entries) => {
                entries.forEach((entry) => {
                    if (entry.isIntersecting) {
                        const index =
                            entry.target.dataset.index;

                        setVisibleItems((prev) =>
                            prev.includes(index)
                                ? prev
                                : [...prev, index]
                        );

                        observer.unobserve(entry.target);
                    }
                });
            },
            {
                threshold: 0.12,
                rootMargin:
                    "0px 0px -50px 0px",
            }
        );

        sectionRefs.current.forEach((element) => {
            if (element) {
                observer.observe(element);
            }
        });

        return () => observer.disconnect();
    }, [data]);

    // ==================================================
    // REVEAL CLASS
    // ==================================================

    const revealClass = (index) =>
        visibleItems.includes(String(index))
            ? "blog-reveal blog-show"
            : "blog-reveal";

    // ==================================================
    // COMMENT FORM
    // ==================================================

    const handleSubmit = (e) => {
        e.preventDefault();
    };

    // ==================================================
    // FALLBACK IMAGES
    // ==================================================

    const heroImage =
        data.hero?.backgroundImage || q1;

    const featureImage =
        data.featureImage || a5;

    // ==================================================
    // RENDER
    // ==================================================

    return (
        <main className="blog-detail-page">

            {/* =================================================
                HERO
            ================================================= */}

            <section className="blog-detail-hero">

                <img
                    src={heroImage}
                    alt="Solar panels and city"
                    className="blog-detail-hero-image"
                />

                <div className="blog-detail-hero-overlay"></div>

                <div className="blog-detail-hero-content">

                    <h1 className="blog-detail-hero-title">
                        {data.hero?.title}
                    </h1>

                    <div className="blog-detail-hero-meta">

                        <div className="blog-meta-item">

                            <CalendarDays size={18} />

                            <span>
                                {data.hero?.date}
                            </span>

                        </div>

                        <span className="blog-meta-divider"></span>

                        <div className="blog-meta-item">

                            <Tag size={18} />

                            <span>
                                {data.hero?.category}
                            </span>

                        </div>

                    </div>

                </div>

            </section>

            {/* =================================================
                BLOG CONTENT
            ================================================= */}

            <section className="blog-detail-container">

                <article className="blog-detail-content">

                    {/* =================================================
                        FEATURE IMAGE
                    ================================================= */}

                    <div
                        ref={(element) =>
                            (sectionRefs.current[0] = element)
                        }
                        data-index="0"
                        className={`${revealClass(
                            0
                        )} blog-feature-image-wrapper`}
                    >

                        <img
                            src={featureImage}
                            alt={data.hero?.title}
                            className="blog-feature-image"
                        />

                    </div>

                    {/* =================================================
                        INTRO
                    ================================================= */}

                    <div
                        ref={(element) =>
                            (sectionRefs.current[1] = element)
                        }
                        data-index="1"
                        className={revealClass(1)}
                    >

                        <p>
                            {data.intro?.paragraph1}
                        </p>

                        <p>
                            {data.intro?.paragraph2}
                        </p>

                    </div>

                    {/* =================================================
                        QUOTE
                    ================================================= */}

                    <div
                        ref={(element) =>
                            (sectionRefs.current[2] = element)
                        }
                        data-index="2"
                        className={revealClass(2)}
                    >

                        <div className="blog-quote-box">

                            <div className="blog-quote-icon">
                                <Quote />
                            </div>

                            <p className="blog-quote-text">
                                {data.quote}
                            </p>

                        </div>

                    </div>

                    {/* =================================================
                        BENEFITS
                    ================================================= */}

                    <div
                        ref={(element) =>
                            (sectionRefs.current[3] = element)
                        }
                        data-index="3"
                        className={revealClass(3)}
                    >

                        <p>
                            {data.benefits}
                        </p>

                    </div>

                    {/* =================================================
                        INSTALLATION
                    ================================================= */}

                    <div
                        ref={(element) =>
                            (sectionRefs.current[4] = element)
                        }
                        data-index="4"
                        className={revealClass(4)}
                    >

                        <h2 className="blog-detail-heading">
                            {data.installation?.heading}
                        </h2>

                        <p>
                            {data.installation?.description}
                        </p>

                    </div>

                    {/* =================================================
                        INSTALLATION LIST
                    ================================================= */}

                    <div
                        ref={(element) =>
                            (sectionRefs.current[5] = element)
                        }
                        data-index="5"
                        className={revealClass(5)}
                    >

                        <ul className="blog-detail-list">

                            {Array.isArray(
                                data.installationSteps
                            ) &&
                                data.installationSteps.map(
                                    (step, index) => (
                                        <li key={index}>
                                            {step}
                                        </li>
                                    )
                                )}

                        </ul>

                    </div>

                    {/* =================================================
                        CARBON FOOTPRINT
                    ================================================= */}

                    <div
                        ref={(element) =>
                            (sectionRefs.current[6] = element)
                        }
                        data-index="6"
                        className={revealClass(6)}
                    >

                        <p>
                            {data.carbonFootprint}
                        </p>

                    </div>

                    {/* =================================================
                        TAGS + SOCIAL
                    ================================================= */}

                    <div
                        ref={(element) =>
                            (sectionRefs.current[7] = element)
                        }
                        data-index="7"
                        className={revealClass(7)}
                    >

                        <div className="blog-detail-separator"></div>

                        <div className="blog-detail-bottom">

                            {/* ================= TAGS ================= */}

                            <div className="blog-tags">

                                <span className="blog-tags-title">
                                    Tags:
                                </span>

                                {Array.isArray(data.tags) &&
                                    data.tags.map(
                                        (tag, index) => (
                                            <span
                                                className="blog-tag"
                                                key={index}
                                            >
                                                {tag}
                                            </span>
                                        )
                                    )}

                            </div>

                            {/* ================= SOCIAL ================= */}

                            <div className="blog-social">

                                <a
                                    href={
                                        data.social?.facebook ||
                                        "#"
                                    }
                                    className="blog-social-btn"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    onClick={(e) => {
                                        if (
                                            !data.social?.facebook ||
                                            data.social.facebook === "#"
                                        ) {
                                            e.preventDefault();
                                        }
                                    }}
                                >
                                    <FaFacebookF />
                                </a>

                                <a
                                    href={
                                        data.social?.whatsapp ||
                                        "#"
                                    }
                                    className="blog-social-btn"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    onClick={(e) => {
                                        if (
                                            !data.social?.whatsapp ||
                                            data.social.whatsapp === "#"
                                        ) {
                                            e.preventDefault();
                                        }
                                    }}
                                >
                                    <FaWhatsapp />
                                </a>

                                <a
                                    href={
                                        data.social?.linkedin ||
                                        "#"
                                    }
                                    className="blog-social-btn"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    onClick={(e) => {
                                        if (
                                            !data.social?.linkedin ||
                                            data.social.linkedin === "#"
                                        ) {
                                            e.preventDefault();
                                        }
                                    }}
                                >
                                    <FaLinkedinIn />
                                </a>

                            </div>

                        </div>

                    </div>

                    {/* =================================================
                        LEAVE A REPLY
                    ================================================= */}

                    <div
                        ref={(element) =>
                            (sectionRefs.current[8] = element)
                        }
                        data-index="8"
                        className={`${revealClass(
                            8
                        )} blog-comment-section`}
                    >

                        <h2 className="blog-comment-title">
                            {data.comments?.title}
                        </h2>

                        <p className="blog-comment-description">
                            {data.comments?.description}
                        </p>

                        <form onSubmit={handleSubmit}>

                            {/* ================= COMMENT ================= */}

                            <div className="blog-form-group">

                                <label className="blog-form-label">
                                    {data.comments?.commentLabel}
                                </label>

                                <textarea
                                    className="blog-comment-textarea"
                                ></textarea>

                            </div>

                            {/* ================= INPUTS ================= */}

                            <div className="blog-input-row">

                                <div className="blog-form-group">

                                    <label className="blog-form-label">
                                        {data.comments?.nameLabel}
                                    </label>

                                    <input
                                        type="text"
                                        className="blog-input"
                                    />

                                </div>

                                <div className="blog-form-group">

                                    <label className="blog-form-label">
                                        {data.comments?.emailLabel}
                                    </label>

                                    <input
                                        type="email"
                                        className="blog-input"
                                    />

                                </div>

                                <div className="blog-form-group">

                                    <label className="blog-form-label">
                                        {data.comments?.websiteLabel}
                                    </label>

                                    <input
                                        type="text"
                                        className="blog-input"
                                    />

                                </div>

                            </div>

                            {/* ================= CHECKBOX ================= */}

                            <div className="blog-checkbox-row">

                                <input
                                    type="checkbox"
                                    id="save-details"
                                    className="blog-checkbox"
                                />

                                <label
                                    htmlFor="save-details"
                                    className="blog-checkbox-label"
                                >
                                    {data.comments?.saveDetailsText}
                                </label>

                            </div>

                            {/* ================= BUTTON ================= */}

                            <button
                                type="submit"
                                className="blog-post-btn"
                            >
                                {data.comments?.buttonText}
                            </button>

                        </form>

                    </div>

                </article>

            </section>

        </main>
    );
};

export default BlogDetail;