import React, { useEffect, useState } from "react";
import axios from "axios";
import {
    ArrowLeft,
    Image as ImageIcon,
    Plus,
    Save,
    Trash2,
} from "lucide-react";
import { useNavigate } from "react-router-dom";

const API_URL = "http://localhost:5000/api";

// ======================================================
// DEFAULT BLOG DETAILS DATA
// ======================================================

const defaultData = {
    hero: {
        title: "A Complete Guide to Solar Energy for Homeowners",
        backgroundImage: "",
        date: "February 27, 2026",
        category: "Residential Solar",
    },

    featureImage: "",

    intro: {
        paragraph1:
            "Switching to solar energy is one of the smartest decisions homeowners can make today. With rising electricity costs & growing environmental concerns, solar power offers a clean, reliable, and cost-effective solution. This guide will walk you through everything you need to know about solar energy from how it works to how you can benefit from it in your daily life.",

        paragraph2:
            "Solar energy is generated by capturing sunlight using solar panels and converting it into usable electricity. These panels produce direct current (DC) power, which is then converted into alternating current (AC) power by an inverter so it can be used in your home. Any excess energy can be sent back to the grid or stored in batteries for later use.",
    },

    quote:
        "Harnessing the power of the sun not only helps you save on electricity bills but also contributes to a cleaner environment, greater energy independence, and a more sustainable future for your home and family.",

    benefits:
        "Solar power helps reduce your monthly electricity bills, protects you from rising energy prices, & lowers your carbon footprint. It also increases your energy independence and can add long-term value to your property. With battery storage, you can even keep your home powered during outages.",

    installation: {
        heading: "Understanding installation and costs",

        description:
            "The installation process usually includes site inspection, system design, approvals, installation, and final testing. While the upfront cost may seem significant, solar systems typically pay for themselves over time through energy savings and incentives, making them a smart long term investment.",
    },

    installationSteps: [
        "While there is an upfront investment, long-term savings on electricity bills & possible incentives help recover costs over time.",

        "Professional technician install a system, connect all component & test performance to ensure everything work safely & efficiently.",

        "Necessary permits, grid approvals, and paperwork are handled to ensure a smooth and compliant installation process.",

        "Based on the assessment a customized system is designed & transparent cost estimate is provided with no hidden charges.",

        "A detailed inspection of your property & energy usage helps determine the right system size, layout & expected performance.",
    ],

    carbonFootprint:
        "One of the most effective ways to lower your carbon footprint is by reducing energy consumption. Simple steps like using energy-efficient appliances, switching to LED lighting, and turning off devices when not in use can significantly cut down on emissions. Choosing renewable energy sources, where available, further helps minimize dependence on fossil fuels and supports cleaner power generation.",

    tags: [
        "Green Energy",
        "Solar Energy",
        "Sustainable Energy",
    ],

    social: {
        facebook: "#",
        whatsapp: "#",
        linkedin: "#",
    },

    comments: {
        title: "Leave a Reply",

        description:
            "Your email address will not be published. Required fields are marked *",

        commentLabel: "Comment *",
        nameLabel: "Name *",
        emailLabel: "Email *",
        websiteLabel: "Website",

        saveDetailsText:
            "Save my name, email, and website in this browser for the next time I comment.",

        buttonText: "Post Comment",
    },
};

// ======================================================
// HELPERS
// ======================================================

const isObject = (value) => {
    return (
        value !== null &&
        typeof value === "object" &&
        !Array.isArray(value)
    );
};

const getPageName = (page) => {
    return String(page?.pageName || page?.page_name || "")
        .trim()
        .toLowerCase();
};

const getSectionName = (page) => {
    return String(page?.sectionName || page?.section_name || "")
        .trim()
        .toLowerCase();
};

const getContentObject = (page) => {
    if (!page?.content) {
        return {};
    }

    if (typeof page.content === "object") {
        return page.content;
    }

    try {
        return JSON.parse(page.content);
    } catch {
        return {};
    }
};

const mergeBlogData = (content) => {
    const safeContent = isObject(content) ? content : {};

    return {
        ...defaultData,
        ...safeContent,

        hero: {
            ...defaultData.hero,
            ...(isObject(safeContent.hero)
                ? safeContent.hero
                : {}),
        },

        intro: {
            ...defaultData.intro,
            ...(isObject(safeContent.intro)
                ? safeContent.intro
                : {}),
        },

        installation: {
            ...defaultData.installation,
            ...(isObject(safeContent.installation)
                ? safeContent.installation
                : {}),
        },

        social: {
            ...defaultData.social,
            ...(isObject(safeContent.social)
                ? safeContent.social
                : {}),
        },

        comments: {
            ...defaultData.comments,
            ...(isObject(safeContent.comments)
                ? safeContent.comments
                : {}),
        },

        installationSteps: Array.isArray(
            safeContent.installationSteps
        )
            ? safeContent.installationSteps
            : [...defaultData.installationSteps],

        tags: Array.isArray(safeContent.tags)
            ? safeContent.tags
            : [...defaultData.tags],
    };
};

// ======================================================
// COMPONENT
// ======================================================

const BlogDetail = () => {
    const navigate = useNavigate();

    const [data, setData] = useState(() =>
        mergeBlogData(defaultData)
    );

    const [pageId, setPageId] = useState(null);
    const [loading, setLoading] = useState(true);
    const [saving, setSaving] = useState(false);

    // ==================================================
    // FIND BLOG DETAILS RECORD
    // ==================================================

    const getLatestBlogDetail = (pages) => {
        const blogPages = pages.filter((page) => {
            const pageName = getPageName(page);
            const sectionName = getSectionName(page);

            const validPageName =
                pageName === "blog details" ||
                pageName === "blog detail" ||
                pageName === "blogdetail";

            const validSectionName =
                sectionName === "blog details" ||
                sectionName === "blog detail" ||
                sectionName === "blogdetail";

            return validPageName && validSectionName;
        });

        if (blogPages.length === 0) {
            return null;
        }

        return blogPages.reduce((latest, current) => {
            return Number(current.id) > Number(latest.id)
                ? current
                : latest;
        });
    };

    // ==================================================
    // LOAD BLOG DETAILS
    // ==================================================

    const loadBlogDetails = async () => {
        try {
            setLoading(true);

            const response = await axios.get(
                `${API_URL}/pages`
            );

            const pages = Array.isArray(response.data)
                ? response.data
                : Array.isArray(response.data?.pages)
                    ? response.data.pages
                    : [];

            const blogDetailPage =
                getLatestBlogDetail(pages);

            // ------------------------------------------
            // NO RECORD YET
            // ------------------------------------------

            if (!blogDetailPage) {
                setPageId(null);
                setData(mergeBlogData(defaultData));
                return;
            }

            // ------------------------------------------
            // EXISTING RECORD
            // ------------------------------------------

            const content =
                getContentObject(blogDetailPage);

            setPageId(blogDetailPage.id);

            setData(
                mergeBlogData(content)
            );
        } catch (error) {
            console.error(
                "BLOG DETAILS LOAD ERROR:",
                error.response?.data || error
            );

            alert(
                error.response?.data?.message ||
                "Failed to load Blog Details data."
            );
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        loadBlogDetails();
    }, []);

    // ==================================================
    // BASIC FIELD UPDATE
    // ==================================================

    const updateField = (field, value) => {
        setData((prev) => ({
            ...prev,
            [field]: value,
        }));
    };

    // ==================================================
    // NESTED FIELD UPDATE
    // ==================================================

    const updateNestedField = (
        section,
        field,
        value
    ) => {
        setData((prev) => ({
            ...prev,
            [section]: {
                ...(prev[section] || {}),
                [field]: value,
            },
        }));
    };

    // ==================================================
    // INSTALLATION STEPS
    // ==================================================

    const updateStep = (index, value) => {
        setData((prev) => {
            const steps = [
                ...(Array.isArray(
                    prev.installationSteps
                )
                    ? prev.installationSteps
                    : []),
            ];

            steps[index] = value;

            return {
                ...prev,
                installationSteps: steps,
            };
        });
    };

    const addStep = () => {
        setData((prev) => ({
            ...prev,

            installationSteps: [
                ...(Array.isArray(
                    prev.installationSteps
                )
                    ? prev.installationSteps
                    : []),

                "Enter installation step...",
            ],
        }));
    };

    const deleteStep = (index) => {
        setData((prev) => ({
            ...prev,

            installationSteps:
                prev.installationSteps.filter(
                    (_, i) => i !== index
                ),
        }));
    };

    // ==================================================
    // TAGS
    // ==================================================

    const updateTag = (index, value) => {
        setData((prev) => {
            const tags = [
                ...(Array.isArray(prev.tags)
                    ? prev.tags
                    : []),
            ];

            tags[index] = value;

            return {
                ...prev,
                tags,
            };
        });
    };

    const addTag = () => {
        setData((prev) => ({
            ...prev,

            tags: [
                ...(Array.isArray(prev.tags)
                    ? prev.tags
                    : []),

                "New Tag",
            ],
        }));
    };

    const deleteTag = (index) => {
        setData((prev) => ({
            ...prev,

            tags: prev.tags.filter(
                (_, i) => i !== index
            ),
        }));
    };

    // ==================================================
    // SAVE BLOG DETAILS
    // ==================================================

    const handleSave = async () => {
        if (saving) {
            return;
        }

        try {
            setSaving(true);

            const token =
                localStorage.getItem("token");

            if (!token) {
                alert(
                    "Admin login token not found. Please login again."
                );

                return;
            }

            // ------------------------------------------
            // CLEAN DATA BEFORE SAVE
            // ------------------------------------------

            const cleanData = {
                hero: {
                    title:
                        data.hero?.title || "",
                    backgroundImage:
                        data.hero?.backgroundImage || "",
                    date:
                        data.hero?.date || "",
                    category:
                        data.hero?.category || "",
                },

                featureImage:
                    data.featureImage || "",

                intro: {
                    paragraph1:
                        data.intro?.paragraph1 || "",
                    paragraph2:
                        data.intro?.paragraph2 || "",
                },

                quote:
                    data.quote || "",

                benefits:
                    data.benefits || "",

                installation: {
                    heading:
                        data.installation?.heading || "",
                    description:
                        data.installation?.description || "",
                },

                installationSteps:
                    Array.isArray(
                        data.installationSteps
                    )
                        ? data.installationSteps
                            .map((step) =>
                                String(step || "")
                            )
                            .filter(
                                (step) =>
                                    step.trim() !== ""
                            )
                        : [],

                carbonFootprint:
                    data.carbonFootprint || "",

                tags:
                    Array.isArray(data.tags)
                        ? data.tags
                            .map((tag) =>
                                String(tag || "")
                            )
                            .filter(
                                (tag) =>
                                    tag.trim() !== ""
                            )
                        : [],

                social: {
                    facebook:
                        data.social?.facebook || "",
                    whatsapp:
                        data.social?.whatsapp || "",
                    linkedin:
                        data.social?.linkedin || "",
                },

                comments: {
                    title:
                        data.comments?.title || "",
                    description:
                        data.comments?.description || "",
                    commentLabel:
                        data.comments?.commentLabel || "",
                    nameLabel:
                        data.comments?.nameLabel || "",
                    emailLabel:
                        data.comments?.emailLabel || "",
                    websiteLabel:
                        data.comments?.websiteLabel || "",
                    saveDetailsText:
                        data.comments?.saveDetailsText || "",
                    buttonText:
                        data.comments?.buttonText || "",
                },
            };

            const payload = {
                page_name: "Blog Details",
                section_name: "Blog Details",

                title:
                    cleanData.hero.title,

                description:
                    "Blog Details page content",

                image:
                    cleanData.hero.backgroundImage,

                content: cleanData,
            };

            const config = {
                headers: {
                    Authorization:
                        `Bearer ${token}`,

                    "Content-Type":
                        "application/json",
                },
            };

            let response;

            // ------------------------------------------
            // UPDATE
            // ------------------------------------------

            if (pageId) {
                response = await axios.put(
                    `${API_URL}/pages/${pageId}`,
                    payload,
                    config
                );
            }

            // ------------------------------------------
            // CREATE
            // ------------------------------------------

            else {
                response = await axios.post(
                    `${API_URL}/pages`,
                    payload,
                    config
                );
            }

            // ------------------------------------------
            // GET NEW ID
            // ------------------------------------------

            const newId =
                response.data?.id ||
                response.data?.page?.id ||
                response.data?.data?.id ||
                null;

            if (newId) {
                setPageId(newId);
            }

            // ------------------------------------------
            // KEEP LOCAL DATA CLEAN
            // ------------------------------------------

            setData(
                mergeBlogData(cleanData)
            );

            alert(
                "Blog Details saved successfully!"
            );
        } catch (error) {
            console.error(
                "BLOG DETAILS SAVE ERROR:",
                error.response?.data || error
            );

            const status =
                error.response?.status;

            if (status === 401) {
                alert(
                    "Session expired. Please login again."
                );
            } else if (status === 403) {
                alert(
                    "Only admin can update Blog Details."
                );
            } else if (
                error.response?.data?.message
            ) {
                alert(
                    error.response.data.message
                );
            } else {
                alert(
                    "Failed to save Blog Details."
                );
            }
        } finally {
            setSaving(false);
        }
    };

    // ==================================================
    // STYLES
    // ==================================================

    const inputClass =
        "w-full rounded-lg border border-slate-200 bg-white px-4 py-3 text-sm text-slate-700 outline-none transition focus:border-green-500 focus:ring-2 focus:ring-green-100";

    const textareaClass =
        "min-h-[120px] w-full rounded-lg border border-slate-200 bg-white px-4 py-3 text-sm leading-6 text-slate-700 outline-none transition focus:border-green-500 focus:ring-2 focus:ring-green-100";

    const labelClass =
        "mb-2 block text-sm font-semibold text-slate-700";

    const sectionClass =
        "rounded-xl border border-slate-200 bg-white p-6 shadow-sm";

    // ==================================================
    // LOADING
    // ==================================================

    if (loading) {
        return (
            <div className="flex min-h-[400px] items-center justify-center">
                <div className="text-sm font-medium text-slate-500">
                    Loading Blog Details...
                </div>
            </div>
        );
    }

    // ==================================================
    // JSX
    // ==================================================

    return (
        <div className="min-h-screen bg-slate-50 p-4 md:p-6">

            {/* ==================================================
                HEADER
            ================================================== */}

            <div className="mb-6 flex flex-col gap-4 rounded-xl border border-slate-200 bg-white p-5 shadow-sm md:flex-row md:items-center md:justify-between">

                <div className="flex items-center gap-3">

                    <button
                        type="button"
                        onClick={() =>
                            navigate(
                                "/admin/pages/home"
                            )
                        }
                        className="flex h-10 w-10 items-center justify-center rounded-lg border border-slate-200 text-slate-600 transition hover:bg-green-50 hover:text-green-600"
                    >
                        <ArrowLeft size={19} />
                    </button>

                    <div>
                        <h1 className="text-xl font-bold text-slate-800">
                            Blog Details
                        </h1>

                        <p className="mt-1 text-sm text-slate-500">
                            Manage the complete Blog Details inner page content.
                        </p>
                    </div>

                </div>

                <button
                    type="button"
                    onClick={handleSave}
                    disabled={saving}
                    className="flex items-center justify-center gap-2 rounded-lg bg-green-500 px-5 py-3 text-sm font-semibold text-white shadow-sm transition hover:bg-green-600 disabled:cursor-not-allowed disabled:opacity-60"
                >
                    <Save size={18} />

                    {saving
                        ? "Saving..."
                        : "Save Changes"}
                </button>

            </div>

            <div className="mx-auto max-w-7xl space-y-6">

                {/* ==================================================
                    HERO
                ================================================== */}

                <section className={sectionClass}>

                    <div className="mb-5 flex items-center gap-3 border-b border-slate-100 pb-4">

                        <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-green-50 text-green-600">
                            <ImageIcon size={20} />
                        </div>

                        <div>
                            <h2 className="text-lg font-bold text-slate-800">
                                Hero Section
                            </h2>

                            <p className="text-sm text-slate-500">
                                Edit the Blog Details hero content.
                            </p>
                        </div>

                    </div>

                    <div className="grid gap-5">

                        <div>
                            <label className={labelClass}>
                                Hero Title
                            </label>

                            <input
                                type="text"
                                value={
                                    data.hero.title
                                }
                                onChange={(e) =>
                                    updateNestedField(
                                        "hero",
                                        "title",
                                        e.target.value
                                    )
                                }
                                className={inputClass}
                            />
                        </div>

                        <div>
                            <label className={labelClass}>
                                Background Image
                            </label>

                            <input
                                type="text"
                                value={
                                    data.hero.backgroundImage
                                }
                                onChange={(e) =>
                                    updateNestedField(
                                        "hero",
                                        "backgroundImage",
                                        e.target.value
                                    )
                                }
                                placeholder="Enter image URL/path"
                                className={inputClass}
                            />
                        </div>

                        <div className="grid gap-5 md:grid-cols-2">

                            <div>
                                <label className={labelClass}>
                                    Date
                                </label>

                                <input
                                    type="text"
                                    value={
                                        data.hero.date
                                    }
                                    onChange={(e) =>
                                        updateNestedField(
                                            "hero",
                                            "date",
                                            e.target.value
                                        )
                                    }
                                    className={inputClass}
                                />
                            </div>

                            <div>
                                <label className={labelClass}>
                                    Category
                                </label>

                                <input
                                    type="text"
                                    value={
                                        data.hero.category
                                    }
                                    onChange={(e) =>
                                        updateNestedField(
                                            "hero",
                                            "category",
                                            e.target.value
                                        )
                                    }
                                    className={inputClass}
                                />
                            </div>

                        </div>

                    </div>
                </section>

                {/* ==================================================
                    FEATURE IMAGE
                ================================================== */}

                <section className={sectionClass}>

                    <h2 className="mb-5 text-lg font-bold text-slate-800">
                        Feature Image
                    </h2>

                    <label className={labelClass}>
                        Feature Image URL / Path
                    </label>

                    <input
                        type="text"
                        value={
                            data.featureImage
                        }
                        onChange={(e) =>
                            updateField(
                                "featureImage",
                                e.target.value
                            )
                        }
                        placeholder="Enter image URL/path"
                        className={inputClass}
                    />

                </section>

                {/* ==================================================
                    INTRODUCTION
                ================================================== */}

                <section className={sectionClass}>

                    <h2 className="mb-5 text-lg font-bold text-slate-800">
                        Introduction
                    </h2>

                    <div className="space-y-5">

                        <div>
                            <label className={labelClass}>
                                Paragraph 1
                            </label>

                            <textarea
                                value={
                                    data.intro.paragraph1
                                }
                                onChange={(e) =>
                                    updateNestedField(
                                        "intro",
                                        "paragraph1",
                                        e.target.value
                                    )
                                }
                                className={textareaClass}
                            />
                        </div>

                        <div>
                            <label className={labelClass}>
                                Paragraph 2
                            </label>

                            <textarea
                                value={
                                    data.intro.paragraph2
                                }
                                onChange={(e) =>
                                    updateNestedField(
                                        "intro",
                                        "paragraph2",
                                        e.target.value
                                    )
                                }
                                className={textareaClass}
                            />
                        </div>

                    </div>
                </section>

                {/* ==================================================
                    QUOTE
                ================================================== */}

                <section className={sectionClass}>

                    <h2 className="mb-5 text-lg font-bold text-slate-800">
                        Quote
                    </h2>

                    <textarea
                        value={data.quote}
                        onChange={(e) =>
                            updateField(
                                "quote",
                                e.target.value
                            )
                        }
                        className={textareaClass}
                    />

                </section>

                {/* ==================================================
                    BENEFITS
                ================================================== */}

                <section className={sectionClass}>

                    <h2 className="mb-5 text-lg font-bold text-slate-800">
                        Benefits
                    </h2>

                    <textarea
                        value={data.benefits}
                        onChange={(e) =>
                            updateField(
                                "benefits",
                                e.target.value
                            )
                        }
                        className={textareaClass}
                    />

                </section>

                {/* ==================================================
                    INSTALLATION
                ================================================== */}

                <section className={sectionClass}>

                    <h2 className="mb-5 text-lg font-bold text-slate-800">
                        Installation
                    </h2>

                    <div className="space-y-5">

                        <div>
                            <label className={labelClass}>
                                Heading
                            </label>

                            <input
                                type="text"
                                value={
                                    data.installation.heading
                                }
                                onChange={(e) =>
                                    updateNestedField(
                                        "installation",
                                        "heading",
                                        e.target.value
                                    )
                                }
                                className={inputClass}
                            />
                        </div>

                        <div>
                            <label className={labelClass}>
                                Description
                            </label>

                            <textarea
                                value={
                                    data.installation.description
                                }
                                onChange={(e) =>
                                    updateNestedField(
                                        "installation",
                                        "description",
                                        e.target.value
                                    )
                                }
                                className={textareaClass}
                            />
                        </div>

                    </div>
                </section>

                {/* ==================================================
                    INSTALLATION STEPS
                ================================================== */}

                <section className={sectionClass}>

                    <div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">

                        <div>
                            <h2 className="text-lg font-bold text-slate-800">
                                Installation Steps
                            </h2>

                            <p className="text-sm text-slate-500">
                                Add, edit or remove installation steps.
                            </p>
                        </div>

                        <button
                            type="button"
                            onClick={addStep}
                            className="flex items-center justify-center gap-2 rounded-lg bg-green-500 px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-green-600"
                        >
                            <Plus size={17} />
                            Add Step
                        </button>

                    </div>

                    <div className="space-y-4">

                        {data.installationSteps.map(
                            (step, index) => (
                                <div
                                    key={index}
                                    className="flex gap-3 rounded-lg border border-slate-200 bg-slate-50 p-3"
                                >

                                    <div className="flex h-10 min-w-10 items-center justify-center rounded-lg bg-green-100 text-sm font-bold text-green-700">
                                        {index + 1}
                                    </div>

                                    <textarea
                                        value={step}
                                        onChange={(e) =>
                                            updateStep(
                                                index,
                                                e.target.value
                                            )
                                        }
                                        className="min-h-[80px] flex-1 rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-700 outline-none focus:border-green-500 focus:ring-2 focus:ring-green-100"
                                    />

                                    <button
                                        type="button"
                                        onClick={() =>
                                            deleteStep(
                                                index
                                            )
                                        }
                                        className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg border border-red-100 text-red-500 transition hover:bg-red-50"
                                        title="Delete Step"
                                    >
                                        <Trash2
                                            size={17}
                                        />
                                    </button>

                                </div>
                            )
                        )}

                    </div>
                </section>

                {/* ==================================================
                    CARBON FOOTPRINT
                ================================================== */}

                <section className={sectionClass}>

                    <h2 className="mb-5 text-lg font-bold text-slate-800">
                        Carbon Footprint
                    </h2>

                    <textarea
                        value={
                            data.carbonFootprint
                        }
                        onChange={(e) =>
                            updateField(
                                "carbonFootprint",
                                e.target.value
                            )
                        }
                        className={textareaClass}
                    />

                </section>

                {/* ==================================================
                    TAGS
                ================================================== */}

                <section className={sectionClass}>

                    <div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">

                        <div>
                            <h2 className="text-lg font-bold text-slate-800">
                                Tags
                            </h2>

                            <p className="text-sm text-slate-500">
                                Manage Blog Details tags.
                            </p>
                        </div>

                        <button
                            type="button"
                            onClick={addTag}
                            className="flex items-center justify-center gap-2 rounded-lg bg-green-500 px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-green-600"
                        >
                            <Plus size={17} />
                            Add Tag
                        </button>

                    </div>

                    <div className="grid gap-3 md:grid-cols-2">

                        {data.tags.map(
                            (tag, index) => (
                                <div
                                    key={index}
                                    className="flex gap-2"
                                >

                                    <input
                                        type="text"
                                        value={tag}
                                        onChange={(e) =>
                                            updateTag(
                                                index,
                                                e.target.value
                                            )
                                        }
                                        className={inputClass}
                                    />

                                    <button
                                        type="button"
                                        onClick={() =>
                                            deleteTag(
                                                index
                                            )
                                        }
                                        className="flex h-[46px] w-11 shrink-0 items-center justify-center rounded-lg border border-red-100 text-red-500 transition hover:bg-red-50"
                                        title="Delete Tag"
                                    >
                                        <Trash2
                                            size={17}
                                        />
                                    </button>

                                </div>
                            )
                        )}

                    </div>
                </section>

                {/* ==================================================
                    SOCIAL
                ================================================== */}

                <section className={sectionClass}>

                    <h2 className="mb-5 text-lg font-bold text-slate-800">
                        Social Links
                    </h2>

                    <div className="grid gap-5 md:grid-cols-3">

                        <div>
                            <label className={labelClass}>
                                Facebook
                            </label>

                            <input
                                type="text"
                                value={
                                    data.social.facebook
                                }
                                onChange={(e) =>
                                    updateNestedField(
                                        "social",
                                        "facebook",
                                        e.target.value
                                    )
                                }
                                className={inputClass}
                            />
                        </div>

                        <div>
                            <label className={labelClass}>
                                WhatsApp
                            </label>

                            <input
                                type="text"
                                value={
                                    data.social.whatsapp
                                }
                                onChange={(e) =>
                                    updateNestedField(
                                        "social",
                                        "whatsapp",
                                        e.target.value
                                    )
                                }
                                className={inputClass}
                            />
                        </div>

                        <div>
                            <label className={labelClass}>
                                LinkedIn
                            </label>

                            <input
                                type="text"
                                value={
                                    data.social.linkedin
                                }
                                onChange={(e) =>
                                    updateNestedField(
                                        "social",
                                        "linkedin",
                                        e.target.value
                                    )
                                }
                                className={inputClass}
                            />
                        </div>

                    </div>
                </section>

                {/* ==================================================
                    COMMENTS
                ================================================== */}

                <section className={sectionClass}>

                    <div className="mb-5">

                        <h2 className="text-lg font-bold text-slate-800">
                            Comments Section
                        </h2>

                        <p className="mt-1 text-sm text-slate-500">
                            Manage all visible text of the comment form.
                        </p>

                    </div>

                    <div className="space-y-5">

                        <div>
                            <label className={labelClass}>
                                Section Title
                            </label>

                            <input
                                type="text"
                                value={
                                    data.comments.title
                                }
                                onChange={(e) =>
                                    updateNestedField(
                                        "comments",
                                        "title",
                                        e.target.value
                                    )
                                }
                                className={inputClass}
                            />
                        </div>

                        <div>
                            <label className={labelClass}>
                                Description
                            </label>

                            <textarea
                                value={
                                    data.comments.description
                                }
                                onChange={(e) =>
                                    updateNestedField(
                                        "comments",
                                        "description",
                                        e.target.value
                                    )
                                }
                                className={textareaClass}
                            />
                        </div>

                        <div className="grid gap-5 md:grid-cols-2">

                            <div>
                                <label className={labelClass}>
                                    Comment Label
                                </label>

                                <input
                                    type="text"
                                    value={
                                        data.comments.commentLabel
                                    }
                                    onChange={(e) =>
                                        updateNestedField(
                                            "comments",
                                            "commentLabel",
                                            e.target.value
                                        )
                                    }
                                    className={inputClass}
                                />
                            </div>

                            <div>
                                <label className={labelClass}>
                                    Name Label
                                </label>

                                <input
                                    type="text"
                                    value={
                                        data.comments.nameLabel
                                    }
                                    onChange={(e) =>
                                        updateNestedField(
                                            "comments",
                                            "nameLabel",
                                            e.target.value
                                        )
                                    }
                                    className={inputClass}
                                />
                            </div>

                            <div>
                                <label className={labelClass}>
                                    Email Label
                                </label>

                                <input
                                    type="text"
                                    value={
                                        data.comments.emailLabel
                                    }
                                    onChange={(e) =>
                                        updateNestedField(
                                            "comments",
                                            "emailLabel",
                                            e.target.value
                                        )
                                    }
                                    className={inputClass}
                                />
                            </div>

                            <div>
                                <label className={labelClass}>
                                    Website Label
                                </label>

                                <input
                                    type="text"
                                    value={
                                        data.comments.websiteLabel
                                    }
                                    onChange={(e) =>
                                        updateNestedField(
                                            "comments",
                                            "websiteLabel",
                                            e.target.value
                                        )
                                    }
                                    className={inputClass}
                                />
                            </div>

                        </div>

                        <div>
                            <label className={labelClass}>
                                Save Details Text
                            </label>

                            <textarea
                                value={
                                    data.comments.saveDetailsText
                                }
                                onChange={(e) =>
                                    updateNestedField(
                                        "comments",
                                        "saveDetailsText",
                                        e.target.value
                                    )
                                }
                                className={textareaClass}
                            />
                        </div>

                        <div>
                            <label className={labelClass}>
                                Button Text
                            </label>

                            <input
                                type="text"
                                value={
                                    data.comments.buttonText
                                }
                                onChange={(e) =>
                                    updateNestedField(
                                        "comments",
                                        "buttonText",
                                        e.target.value
                                    )
                                }
                                className={inputClass}
                            />
                        </div>

                    </div>
                </section>

                {/* ==================================================
                    BOTTOM SAVE
                ================================================== */}

                <div className="flex justify-end pb-6">

                    <button
                        type="button"
                        onClick={handleSave}
                        disabled={saving}
                        className="flex items-center justify-center gap-2 rounded-lg bg-green-500 px-6 py-3 text-sm font-semibold text-white shadow-sm transition hover:bg-green-600 disabled:cursor-not-allowed disabled:opacity-60"
                    >
                        <Save size={18} />

                        {saving
                            ? "Saving..."
                            : "Save Changes"}
                    </button>

                </div>

            </div>
        </div>
    );
};

export default BlogDetail;
